services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'RachelRoth'
      POSTGRES_DB: 'main'
    ports:
      - '5588:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - '4222:4222'

volumes:
  postgres_data: